title: cruller.club
email: karim@egyptiankarim.com
description: >-
  Welcome! cruller.club is a savvy design and dev consultancy rooted in the principles of open-source software, community development, and tasty pastries.

baseurl: ""
url: "https://cruller.club"

github_username: cruller-club

plugins:
  - jekyll-feed

collections:
  projects:
    output: true